services:
  developer_application:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: ["mix", "send.application"]
  test:
    image: developer_application:latest
    entrypoint: ["mix"]
    command: ["test"]
    environment:
      MIX_ENV: test
    volumes:
      - .:/app
