services:
  developer_application:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: ["mix", "send.application"]
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIX_ENV: test
    environment:
      MIX_ENV: test
    entrypoint: ["mix", "test"]
